name: Build and Deploy
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: DIYgod/DPlayer
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: pnpm i && pnpm docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: dplayer.js.org
